name: CI/CD
run-name: CI/CD ${{ github.ref }}
on: push
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build
        run: composer install

      - name: Cache webroot
        uses: actions/cache@v3
        with:
          key: webroot-${{ github.run_number }}.${{ github.run_attempt }}
          path: |
            config
            public_html
            vendor
            wp-cli.yml

  continuous-deployment:
    needs: continuous-integration
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Take webroot from cache
        uses: actions/cache@v3
        with:
          key: webroot-${{ github.run_number }}.${{ github.run_attempt }}
          path: |
            config
            public_html
            vendor
            wp-cli.yml
      
      - name: Checkout secrets
        uses: actions/checkout@v3
        with:
          repository: focaliber/focaliber-website-secrets
          ssh-key: ${{ secrets.READ_SECRETS_REPO_KEY }}
          path: './secrets'

      - name: Deploy secrets
        run: |
          cp ./secrets/.ssh/* ~/.ssh/
          chmod 600 ~/.ssh/*.key
          cp ./secrets/.env ./
      
      - name: Deploy on hosting provider
        run: |
          rsync --recursive --checksum --delete --force --compress --human-readable --verbose \
          --include='/config/' \
          --include='/public_html/' \
          --exclude='/public_html/uploads/' \
          --include='/vendor/' \
          --include='/.env' \
          --include='/wp-cli.yml' \
          --exclude='/*' \
          ./ hostingprovider:~/domains/focaliber.nl/
